
CREATE TABLE public.perfil (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "name" varchar(255) NULL,
    CONSTRAINT perfil_name_key UNIQUE (name),
    CONSTRAINT perfil_pkey PRIMARY KEY (id)
);

CREATE TABLE Endereco (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    rua VARCHAR(255) NOT NULL,
    numero VARCHAR(20) NOT null,
    complemento VARCHAR(255),
    cep VARCHAR(10) NOT NULL
);

CREATE TABLE public.usuario (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    email varchar(255) NULL,
    nome varchar(255) NOT NULL,
    senha varchar(255) NOT NULL,
    perfil_id int8 NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    foreign key (perfil_id) references perfil(id)
);

CREATE TABLE public.dispositivo (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    user_id int8 NULL,
    device_id varchar(255) NOT NULL,
    CONSTRAINT dispositivo_pkey PRIMARY KEY (id)
);

ALTER TABLE public.dispositivo ADD CONSTRAINT fk_usuario FOREIGN KEY (user_id) REFERENCES public.usuario(id);

CREATE TABLE solicitacao (
     id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
     solicitante_id int8 NOT NULL,
     status VARCHAR(20) NOT NULL,
     perfil_objetivo_id int8 NOT NULL,
     CONSTRAINT solicitacao_pk PRIMARY KEY (id),
    FOREIGN KEY (solicitante_id) REFERENCES usuario(id),
    FOREIGN KEY (perfil_objetivo_id) references public.perfil(id)
);

create table registro_solicitacao(
     id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
     revisor_id int8 not null,
     solicitacao_id int8 not null,
     justificativa VARCHAR(255),
     CONSTRAINT registro_solicitacao_pkey PRIMARY KEY (id),
         foreign key (revisor_id) references usuario(id),
     foreign key (solicitacao_id) references solicitacao(id)
);


CREATE TABLE public.exposicao (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    descricao varchar(255) NULL,
    nome varchar(255) NULL,
    endereco_id int8,
    CONSTRAINT exposicao_pkey PRIMARY KEY (id),
    foreign key (endereco_id) references Endereco(id)

);


CREATE TABLE public.obra (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    nome varchar(255) NOT NULL,
    nome_artista varchar(255),
    descricao varchar(255),
    link varchar(255),
    qrCode varchar(255),
    exposicao_id int8 NULL,
    CONSTRAINT obra_pkey PRIMARY KEY (id),
);

ALTER TABLE public.obra ADD CONSTRAINT fk_obra FOREIGN KEY (exposicao_id) REFERENCES public.exposicao(id);

CREATE TABLE imagem (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    obra_id int8 not null,
    tamanho_bytes BIGINT,
    conteudo BYTEA NOT NULL,
    data_upload TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    foreign key (obra_id) references obra(id)
);
CREATE TABLE public.mokadex (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    usuario_id int8 NULL,
    CONSTRAINT mokadex_pkey PRIMARY KEY (id),
    CONSTRAINT fk_usuario UNIQUE (usuario_id)
);

CREATE TABLE public.mokadex_obra
(
    mokadex_id int8 NOT NULL,
    obra_id    int8 NOT NULL,
    CONSTRAINT mokadex_obra_pkey PRIMARY KEY (mokadex_id, obra_id)
);

ALTER TABLE public.mokadex_obra
    ADD CONSTRAINT fk_mokadex FOREIGN KEY (mokadex_id) REFERENCES public.mokadex (id);
ALTER TABLE public.mokadex_obra
    ADD CONSTRAINT fk_obra FOREIGN KEY (obra_id) REFERENCES public.obra (id);

CREATE TABLE imagem (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    obra_id int8 not null,
    nome_arquivo VARCHAR(255) NOT NULL,
    tamanho_bytes BIGINT,
    conteudo BYTEA NOT NULL, -- A coluna que armazenará os dados binários
    data_upload TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    foreign key (obra_id) references obra(id)
);


-- public.usario_perfil chaves estrangeiras
-- {
-- 	"email":"test@test.com",
-- 	"password":"Teste123",
-- 	"name":"teste",
-- 	"deviceId":"AKJDASD"
-- }
INSERT INTO public.perfil("name") VALUES( 'USER');
INSERT INTO public.perfil("name") VALUES('RESEARCHER');
INSERT INTO public.perfil("name") VALUES('ADMINISTRATOR');
INSERT INTO public.perfil ("name") VALUES( 'CURATOR');

INSERT INTO public.usuario ( email, nome, senha, perfil_id) VALUES( 'test@test.com', 'teste', '$2a$10$C.g8gn8iC9zu0..ALTIcButWBetd/fyH3a40Dc/sWhFCc3YsiNy6e', 3);

