CREATE TABLE public.perfil
(
    id   INT8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    name VARCHAR(255)                                                                                                             NULL,
    CONSTRAINT perfil_name_key UNIQUE (name),
    CONSTRAINT perfil_pkey PRIMARY KEY (id)
);

CREATE TABLE public.endereco
(
    id          INT8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    rua         VARCHAR(255)                                                                                                             NOT NULL,
    numero      VARCHAR(20)                                                                                                              NOT NULL,
    complemento VARCHAR(255),
    cep         VARCHAR(8)                                                                                                               NOT NULL,
    CONSTRAINT endereco_pkey PRIMARY KEY (id)
);

CREATE TABLE public.local
(
    id          INT8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    nome        VARCHAR(255)                                                                                                             NOT NULL,
    endereco_id INT8                                                                                                                     NOT NULL,
    CONSTRAINT pk_local PRIMARY KEY (id),
    CONSTRAINT unq_nome_local UNIQUE (nome),
    CONSTRAINT fk_endereco FOREIGN KEY (endereco_id) REFERENCES endereco (id) ON DELETE CASCADE
);

CREATE TABLE public.usuario
(
    id        INT8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    email     VARCHAR(255)                                                                                                             NULL,
    nome      VARCHAR(255)                                                                                                             NOT NULL,
    senha     VARCHAR(255)                                                                                                             NOT NULL,
    perfil_id INT8                                                                                                                     NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id),
    CONSTRAINT fk_perfil FOREIGN KEY (perfil_id) REFERENCES perfil (id),
    CONSTRAINT unq_nome_usuario UNIQUE (nome)
);

CREATE TABLE public.dispositivo
(
    id        INT8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    user_id   INT8                                                                                                                     NULL,
    device_id VARCHAR(255)                                                                                                             NOT NULL,
    CONSTRAINT dispositivo_pkey PRIMARY KEY (id)
);

ALTER TABLE public.dispositivo
    ADD CONSTRAINT fk_usuario FOREIGN KEY (user_id) REFERENCES public.usuario (id);

CREATE TABLE public.solicitacao
(
    id                 INT8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    solicitante_id     INT8                                                                                                                     NOT NULL,
    status             VARCHAR(20)                                                                                                              NOT NULL,
    perfil_objetivo_id INT8                                                                                                                     NOT NULL,
    CONSTRAINT solicitacao_pk PRIMARY KEY (id),
    FOREIGN KEY (solicitante_id) REFERENCES usuario (id),
    FOREIGN KEY (perfil_objetivo_id) REFERENCES public.perfil (id)
);

CREATE TABLE public.registro_solicitacao
(
    id             INT8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    revisor_id     INT8                                                                                                                     NOT NULL,
    solicitacao_id INT8                                                                                                                     NOT NULL,
    justificativa  VARCHAR(255),
    CONSTRAINT registro_solicitacao_pkey PRIMARY KEY (id),
    FOREIGN KEY (revisor_id) REFERENCES usuario (id),
    FOREIGN KEY (solicitacao_id) REFERENCES solicitacao (id)
);

CREATE TABLE public.exposicao
(
    id          INT8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    descricao   VARCHAR(255)                                                                                                    NULL,
    nome        VARCHAR(255)                                                                                                    NULL,
    endereco_id INT8,
    CONSTRAINT exposicao_pkey PRIMARY KEY (id),
    FOREIGN KEY (endereco_id) REFERENCES endereco (id)
);

CREATE TABLE public.obra
(
    id           INT8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    nome         VARCHAR(255)                                                                                                    NOT NULL,
    nome_artista VARCHAR(255),
    descricao    VARCHAR(255),
    link         VARCHAR(255),
    qr_code      VARCHAR(255),
    exposicao_id INT8                                                                                                            NULL,
    CONSTRAINT obra_pkey PRIMARY KEY (id)
);

ALTER TABLE public.obra
    ADD CONSTRAINT fk_obra FOREIGN KEY (exposicao_id) REFERENCES public.exposicao (id);

CREATE TABLE public.mokadex
(
    id         INT8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    usuario_id INT8                                                                                                            NOT NULL,
    CONSTRAINT mokadex_pkey PRIMARY KEY (id),
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario (id)
        ON DELETE CASCADE,
    CONSTRAINT unq_usuario UNIQUE (usuario_id)
);

CREATE TABLE public.mokadex_obra
(
    mokadex_id INT8 NOT NULL,
    obra_id    INT8 NOT NULL,
    CONSTRAINT mokadex_obra_pkey PRIMARY KEY (mokadex_id, obra_id),
    CONSTRAINT fk_mokadex FOREIGN KEY (mokadex_id) REFERENCES public.mokadex (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_obra FOREIGN KEY (obra_id) REFERENCES public.obra (id)
        ON DELETE CASCADE
);

CREATE TABLE public.imagem
(
    id            INT8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    obra_id       INT8,
    tamanho_bytes BIGINT,
    conteudo      BYTEA                                                                                                           NOT NULL, -- A coluna que armazenará os dados binários
    data_upload   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (obra_id) REFERENCES obra (id)
);

CREATE TABLE public.emblema
(
    id           INT8 GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    nome         VARCHAR(255)                                                                                                            NOT NULL,
    descricao    VARCHAR(1000),
    exposicao_id INT8                                                                                                                    NOT NULL,
    CONSTRAINT pk_emblema PRIMARY KEY (id),
    CONSTRAINT fk_exposicao FOREIGN KEY (exposicao_id) REFERENCES exposicao (id)
        ON DELETE CASCADE,
    CONSTRAINT unq_exposicao UNIQUE (exposicao_id)
);

CREATE TABLE public.mokadex_emblema
(
    mokadex_id INT8 NOT NULL,
    emblema_id INT8 NOT NULL,
    CONSTRAINT pk_mokadex_emblema PRIMARY KEY (mokadex_id, emblema_id),
    CONSTRAINT fk_mokadex FOREIGN KEY (mokadex_id) REFERENCES mokadex (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_emblema FOREIGN KEY (emblema_id) REFERENCES emblema (id)
        ON DELETE CASCADE
);

-- public.usario_perfil chaves estrangeiras
-- {
-- 	"email":"test@test.com",
-- 	"password":"Teste123",
-- 	"name":"teste",
-- 	"deviceId":"AKJDASD"
-- }
INSERT INTO public.perfil(name) VALUES ('USER');
INSERT INTO public.perfil(name) VALUES ('RESEARCHER');
INSERT INTO public.perfil(name) VALUES ('ADMINISTRATOR');
INSERT INTO public.perfil (name) VALUES ('CURATOR');

INSERT INTO public.usuario (email, nome, senha, perfil_id)
VALUES (
       'test@test.com', 'teste', '$2a$10$C.g8gn8iC9zu0..ALTIcButWBetd/fyH3a40Dc/sWhFCc3YsiNy6e', 3);
