
CREATE TABLE public.perfil (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "name" varchar(255) NULL,
    CONSTRAINT perfil_name_key UNIQUE (name),
    CONSTRAINT perfil_pkey PRIMARY KEY (id)
);

CREATE TABLE public.acao (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "name" varchar(255) NULL,
    CONSTRAINT acao_pkey PRIMARY KEY (id)
);

CREATE TABLE public.perfil_acao (
    acao_id int8 NOT NULL,
    perfil_id int8 NOT NULL,
    CONSTRAINT perfil_acao_pkey PRIMARY KEY (acao_id, perfil_id)
);

ALTER TABLE public.perfil_acao ADD CONSTRAINT fk_acao FOREIGN KEY (acao_id) REFERENCES public.acao(id);
ALTER TABLE public.perfil_acao ADD CONSTRAINT fk_perfil FOREIGN KEY (perfil_id) REFERENCES public.perfil(id);

CREATE TABLE public.usuario (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    email varchar(255) NULL,
    nome varchar(255) NOT NULL,
    senha varchar(255) NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id)
);

CREATE TABLE public.dispositivo (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    user_id int8 NULL,
    device_id varchar(255) NOT NULL,
    CONSTRAINT dispositivo_pkey PRIMARY KEY (id)
);

ALTER TABLE public.dispositivo ADD CONSTRAINT fk_usuario FOREIGN KEY (user_id) REFERENCES public.usuario(id);

CREATE TABLE public.usuario_perfil (
    perfil_id int8 NOT NULL,
    usario_id int8 NOT NULL,
    CONSTRAINT usario_perfil_pkey PRIMARY KEY (perfil_id,usario_id)
);

CREATE TABLE public.exposicao (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    descricao varchar(255) NULL,
    nome varchar(255) NULL,
    CONSTRAINT exposicao_pkey PRIMARY KEY (id)
);


CREATE TABLE public.obra (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    nome varchar(255) NOT NULL,
    exposicao_id int4 NULL,
    CONSTRAINT obra_pkey PRIMARY KEY (id)
);

ALTER TABLE public.obra ADD CONSTRAINT fk_obra FOREIGN KEY (exposicao_id) REFERENCES public.exposicao(id);

CREATE TABLE public.mokadex (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    usuario_id int8 NULL,
    CONSTRAINT mokadex_pkey PRIMARY KEY (id),
    CONSTRAINT fk_usuario UNIQUE (usuario_id)
);

CREATE TABLE public.mokadex_obra
(
    mokadex_id int4 NOT NULL,
    obra_id    int4 NOT NULL,
    CONSTRAINT mokadex_obra_pkey PRIMARY KEY (mokadex_id, obra_id)
);

ALTER TABLE public.mokadex_obra
    ADD CONSTRAINT fk_mokadex FOREIGN KEY (mokadex_id) REFERENCES public.mokadex (id);
ALTER TABLE public.mokadex_obra
    ADD CONSTRAINT fk_obra FOREIGN KEY (obra_id) REFERENCES public.obra (id);
INSERT INTO public.perfil("name") VALUES( 'USER');
INSERT INTO public.acao("name") VALUES('acao_teste');
INSERT INTO public.perfil_acao(acao_id, perfil_id) VALUES(1, 1);



-- public.usario_perfil chaves estrangeiras
-- {
-- 	"email":"test@test.com",
-- 	"password":"Teste123",
-- 	"name":"teste",
-- 	"deviceId":"AKJDASD"
-- }
INSERT INTO public.usuario ( email, nome, senha) VALUES( 'test@test.com', 'teste', '$2a$10$C.g8gn8iC9zu0..ALTIcButWBetd/fyH3a40Dc/sWhFCc3YsiNy6e');
INSERT INTO public.usuario_perfil (perfil_id, usario_id) VALUES(1, 1);
INSERT INTO public.perfil("name") VALUES('RESEARCHER');
INSERT INTO public.perfil("name") VALUES('ADMINISTRATOR');
INSERT INTO public.perfil ("name") VALUES( 'CURATOR');
-- senha: researcher
INSERT INTO public.usuario(email, nome, senha) VALUES('researcher@teste.com', 'researcher', '$2a$10$F.uLDuRLVnzhrJOOPkTD7uknLKPwOWHTzHXG8WFUT5yN.JAcXFe/u');